[package]
name = "reading_notes"
version = "0.1.0"
edition = "2021"

[dependencies]
ollama-rs = "0.2.6"
schemars = "0.8.22"
serde = "1.0.219"
serde_json = "1.0.140"
snafu = "0.8.5"
tokio = { version = "1.38.0", features = ["rt", "macros", "rt-multi-thread"] }
